[package]
name = "i1-templates-8n-derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
typed-langid = { path = "../typed-langid" }
darling = "0.20"
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"
strum = { workspace = true }
